### ISSUE TITLE
경기도 마을 버스는 조회 방법이 있을까요?

### ISSUE THREAD

**Issue by yuilsoo** [iceship/MMM-GyeonggiBus#2]
버스정류장 체크한후에 
정류장 ID 넣고 routeid 체크하려고 보니 
조회 결과에 마을버스와 몇몇 광역버스는 조회가 안되네요. 
할 수 있는 방법이 있을까요?

**Comment by iceship** [comment]
공공데이터포털에서 확인해보셔야 됩니다.
